global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#алерты'
    send_resolved: true
    username: 'Alertmanager'
    text: '{{ .CommonAnnotations.summary }}'
