version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:username"
    
phases:
  build:
    commands:
      - printf '{"ImageURI":"%s"}' aliakseyeu/phpjenkins:latest > imageDetail.json
artifacts:
    files:
        - imageDetail.json
    secondary-artifacts:
      artifact1:
        files:
          - index.html
      ImageArtifact:
        files:
          - imageDetail.json
