global:
  scrape_interval: 30s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: nodes
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          name: 'ec2_master'
      - targets: [ '54.198.131.116:9100' ]
        labels:
          name: 'ec2_slave'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'
