global:
  scrape_interval: 30s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets: 
          - 'node-exporter:9100'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'
